name: Actualiza_incidencia_vacunacion

on:
    push:
        branches: master
        paths: 'output/producto76/vacunacion_t.csv'
        
jobs:
  Actualiza_producto_89_y_90:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate product 80 and 90
      run: |
          cd src
          python vacunacion_casos.py
          
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
    
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: "Balance incidencia en vacunados ${{ steps.date.outputs.date }}"
        
        file_pattern: output/*/*.csv
        
        repository: .
        
        commit_user_name: MinCiencia GitHub Actions Bot
        commit_user_email: actions@github.com
        commit_author: minciencia github bot <actions@github.com>
